# Generated by Django 4.2.5 on 2023-09-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_of_animal', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('profile_picture', models.CharField(max_length=200)),
            ],
        ),
    ]
